BASE_URL = "https://kmctce.etlab.app"
USER_INFO_URL = f"{BASE_URL}/student/profile"
ATTENDANCE_DUTY_LEAVE_URL = f"{BASE_URL}/ktuacademics/student/viewattendancesubjectdutyleave/37"
ATTENDANCE_URL = f"{BASE_URL}/ktuacademics/student/viewattendancesubject/37"
RESULTS_URL = f"{BASE_URL}/ktuacademics/student/results?sem_id=62"
TIMETABLE_URL = f"{BASE_URL}/student/timetable"